Repository jeremykendall/php-domain-parser, pull requests merged in 2019-04, with the labels that each got.

#236 Idna options
  src/Domain.php
  src/IDNAConverterTrait.php
  src/Manager.php
  src/PublicSuffix.php
  src/Rules.php
  src/TLDConverter.php
  src/TopLevelDomains.php
  tests/DomainTest.php
  tests/PublicSuffixTest.php
  tests/RulesTest.php
  tests/TopLevelDomainsTest.php
Labels: enhancement, version 5.0

#241 adding ::labels method see #238
  src/Domain.php
  src/PublicSuffix.php
  tests/DomainTest.php
  tests/PublicSuffixTest.php
Labels: awating author feedback, enhancement, version 5.0

#243 prepare 5.5.0 release
  .github/CONTRIBUTING.md
  .php_cs
  .travis.yml
  CHANGELOG.md
  README.md
  composer.json
  data/pdp-PSL_FULL_5a3cc7f81795bb2e48e848af42d287b4.cache
  data/pdp-RZD_FULL_f18a70477d29d525b9220612e2115345.cache
  src/Cache.php
  src/Converter.php
  src/Domain.php
  src/IDNAConverterTrait.php
  src/Manager.php
  src/PublicSuffix.php
  src/Rules.php
  src/TLDConverter.php
  src/TopLevelDomains.php
  tests/CacheTest.php
  tests/DomainTest.php
  tests/PublicSuffixTest.php
  tests/RulesTest.php
  tests/TopLevelDomainsTest.php
Labels: enhancement
